FROM rust:1.88 AS builder

WORKDIR /app

COPY . .

RUN cargo build --release


FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder \
 /app/target/release/todo-api .

EXPOSE 8080

CMD ["./todo-api"]